# **********************************************************************
#
# Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************
#
# Ice version 3.4.2
#
# <auto-generated>
#
# Generated from file `Temperature.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

import Ice, IcePy, __builtin__

# Start of module Temp
_M_Temp = Ice.openModule('Temp')
__name__ = 'Temp'

if not _M_Temp.__dict__.has_key('Temperature'):
    _M_Temp.Temperature = Ice.createTempClass()
    class Temperature(Ice.Object):
        def __init__(self):
            if __builtin__.type(self) == _M_Temp.Temperature:
                raise RuntimeError('Temp.Temperature is an abstract class')

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::Temp::Temperature')

        def ice_id(self, current=None):
            return '::Temp::Temperature'

        def ice_staticId():
            return '::Temp::Temperature'
        ice_staticId = staticmethod(ice_staticId)

        def getTemperature1C(self, current=None):
            pass

        def getTemperature1F(self, current=None):
            pass

        def getTemperature2C(self, current=None):
            pass

        def getTemperature2F(self, current=None):
            pass

        def __str__(self):
            return IcePy.stringify(self, _M_Temp._t_Temperature)

        __repr__ = __str__

    _M_Temp.TemperaturePrx = Ice.createTempClass()
    class TemperaturePrx(Ice.ObjectPrx):

        def getTemperature1C(self, _ctx=None):
            return _M_Temp.Temperature._op_getTemperature1C.invoke(self, ((), _ctx))

        def begin_getTemperature1C(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_Temp.Temperature._op_getTemperature1C.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_getTemperature1C(self, _r):
            return _M_Temp.Temperature._op_getTemperature1C.end(self, _r)

        def getTemperature1F(self, _ctx=None):
            return _M_Temp.Temperature._op_getTemperature1F.invoke(self, ((), _ctx))

        def begin_getTemperature1F(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_Temp.Temperature._op_getTemperature1F.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_getTemperature1F(self, _r):
            return _M_Temp.Temperature._op_getTemperature1F.end(self, _r)

        def getTemperature2C(self, _ctx=None):
            return _M_Temp.Temperature._op_getTemperature2C.invoke(self, ((), _ctx))

        def begin_getTemperature2C(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_Temp.Temperature._op_getTemperature2C.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_getTemperature2C(self, _r):
            return _M_Temp.Temperature._op_getTemperature2C.end(self, _r)

        def getTemperature2F(self, _ctx=None):
            return _M_Temp.Temperature._op_getTemperature2F.invoke(self, ((), _ctx))

        def begin_getTemperature2F(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_Temp.Temperature._op_getTemperature2F.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_getTemperature2F(self, _r):
            return _M_Temp.Temperature._op_getTemperature2F.end(self, _r)

        def checkedCast(proxy, facetOrCtx=None, _ctx=None):
            return _M_Temp.TemperaturePrx.ice_checkedCast(proxy, '::Temp::Temperature', facetOrCtx, _ctx)
        checkedCast = staticmethod(checkedCast)

        def uncheckedCast(proxy, facet=None):
            return _M_Temp.TemperaturePrx.ice_uncheckedCast(proxy, facet)
        uncheckedCast = staticmethod(uncheckedCast)

    _M_Temp._t_TemperaturePrx = IcePy.defineProxy('::Temp::Temperature', TemperaturePrx)

    _M_Temp._t_Temperature = IcePy.defineClass('::Temp::Temperature', Temperature, (), True, None, (), ())
    Temperature._ice_type = _M_Temp._t_Temperature

    Temperature._op_getTemperature1C = IcePy.Operation('getTemperature1C', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, (), (), (), IcePy._t_float, ())
    Temperature._op_getTemperature1F = IcePy.Operation('getTemperature1F', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, (), (), (), IcePy._t_float, ())
    Temperature._op_getTemperature2C = IcePy.Operation('getTemperature2C', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, (), (), (), IcePy._t_float, ())
    Temperature._op_getTemperature2F = IcePy.Operation('getTemperature2F', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, (), (), (), IcePy._t_float, ())

    _M_Temp.Temperature = Temperature
    del Temperature

    _M_Temp.TemperaturePrx = TemperaturePrx
    del TemperaturePrx

# End of module Temp
