# **********************************************************************
#
# Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************
#
# Ice version 3.4.2
#
# <auto-generated>
#
# Generated from file `Net.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

import Ice, IcePy, __builtin__

# Start of module x10
_M_x10 = Ice.openModule('x10')
__name__ = 'x10'

if not _M_x10.__dict__.has_key('Net'):
    _M_x10.Net = Ice.createTempClass()
    class Net(Ice.Object):
        def __init__(self):
            if __builtin__.type(self) == _M_x10.Net:
                raise RuntimeError('x10.Net is an abstract class')

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::x10::Net')

        def ice_id(self, current=None):
            return '::x10::Net'

        def ice_staticId():
            return '::x10::Net'
        ice_staticId = staticmethod(ice_staticId)

        def printString(self, s, current=None):
            pass

        def __str__(self):
            return IcePy.stringify(self, _M_x10._t_Net)

        __repr__ = __str__

    _M_x10.NetPrx = Ice.createTempClass()
    class NetPrx(Ice.ObjectPrx):

        def printString(self, s, _ctx=None):
            return _M_x10.Net._op_printString.invoke(self, ((s, ), _ctx))

        def begin_printString(self, s, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_x10.Net._op_printString.begin(self, ((s, ), _response, _ex, _sent, _ctx))

        def end_printString(self, _r):
            return _M_x10.Net._op_printString.end(self, _r)

        def checkedCast(proxy, facetOrCtx=None, _ctx=None):
            return _M_x10.NetPrx.ice_checkedCast(proxy, '::x10::Net', facetOrCtx, _ctx)
        checkedCast = staticmethod(checkedCast)

        def uncheckedCast(proxy, facet=None):
            return _M_x10.NetPrx.ice_uncheckedCast(proxy, facet)
        uncheckedCast = staticmethod(uncheckedCast)

    _M_x10._t_NetPrx = IcePy.defineProxy('::x10::Net', NetPrx)

    _M_x10._t_Net = IcePy.defineClass('::x10::Net', Net, (), True, None, (), ())
    Net._ice_type = _M_x10._t_Net

    Net._op_printString = IcePy.Operation('printString', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, (), (((), IcePy._t_string),), (), None, ())

    _M_x10.Net = Net
    del Net

    _M_x10.NetPrx = NetPrx
    del NetPrx

# End of module x10
